spring:
  security:
    oauth2:
      resourceServer:
        jwt:
          # https://accounts.google.com/.well-known/openid-configuration
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs